### ISSUE TITLE
Add Deno basics to CONTRIBUTING.md

### ISSUE THREAD

**Issue by benmccann** [ascorbic/unpic#105]
I can't figure out how to build or test this project. I'm assuming I need to install Deno, but then I'm lost after that. From what I've read on the deno site it seems I don't need to do the equivalent of `npm install`? But then there's also no `package.json` defining the scripts, so I don't know what to run to build or test the project.

**Comment by ascorbic** [comment]
Good idea. The contributing guide gives the command for testing but I could go into more detail. I'll add some more info there. Basically you need to install Deno, then run `deno test src --allow-net`. There's no install or build step. There is a script that creates a module to publish to NPM, but that's just run in CI and shouldn't need running manually. The demo/playground site is in `demo`, which isn't a Deno thing - it's a basic preact+parcel site with a package.json.

**Comment by benmccann** [comment]
thank you! super helpful!
