### ISSUE TITLE
Imagekit - wrong format parameter (fm instead of f)

### ISSUE THREAD

**Issue by gbouteiller** [ascorbic/unpic#114]
Hello and thank you for the great library,
As I mentioned in the title the format parameter for Imagekit is incorrect :
https://docs.imagekit.io/features/image-transformations/resize-crop-and-other-transformations#format-f
If you prefer  a PR, let me know.
Thank you

**Comment by ascorbic** [comment]
Thanks! A PR is always welcome, or I'll fix it when I get a chance.

**Comment by gbouteiller** [comment]
@ascorbic done

**Comment by ascorbic** [comment]
Closed in #116
