### ISSUE TITLE
Support Cloudflare Images

### ISSUE THREAD

**Issue by johneatmon** [ascorbic/unpic#12]
https://github.com/ascorbic/unpic/blob/d59485f22decb0cd7146d5443c438d41f247747e/src/transformers/cloudflare.ts#L9

I believe that Cloudflare images, when served via a custom domain, are delivered with:

https://example.com/cdn-cgi/imagedelivery/<ACCOUNT_HASH>/<IMAGE_ID>/<VARIANT_NAME>

Correct me if I'm wrong, but I believe this RegEx is only checking for `/cdn-cgi/image` rather than `/cdn-cgi/imagedelivery`. Would also be great to also check for the default Cloudflare image delivery URL if you're not using a custom domain:

`https://imagedelivery.net/<ACCOUNT_HASH>/<IMAGE_ID>/<VARIANT_NAME>`

[Link to relevant docs](https://developers.cloudflare.com/images/cloudflare-images/serve-images/serve-images-custom-domains/)

**Comment by ascorbic** [comment]
The examples you've given are for the confusingly named "Cloudflare Images" rather than "Cloudflare Image Resizing", which is what the current one handles. I'd not realised that Cloudflare Images supported dynamic resizing too, but I see it can be enabled with "flexible variants". If someone wants to contribute support for the flexible variants syntax with Cloduflare Images that would be great. If that happened, we could add `imagedelivery.net` to detected domains too.

**Comment by johneatmon** [comment]
I see that now, my apologies. Wow! That is confusing then on their part to have similar products with similar names.

I would contribute the syntax myself, but I am afraid my coding skills are not up to snuff. 😅

**Comment by davedbase** [comment]
I'm using the Image Resizing service as well and having a bit of trouble. I have a properly formatted path for my CF image: `https://cdn.romamoulding.com/cdn-cgi/image//https://cdn.romamoulding.com/mouldings/753-1.png` however I'm receiving `Invalid Cloudflare URL` as an error.

This seems related to the strictness of the transformations group requiring certain input. I'd like to recommend making it optional:
```
https?:\/\/(?<host>[^\/]+)\/cdn-cgi\/image\/(?<transformations>[^\/]+)?\/(?<path>.*)$
```
I can certainly submit a PR to fix it.

The thing about CF Image Resizing is that it also allows you to proxy the requests through a customer worker for serving up images ie. I have this setup: https://images.romamoulding.com/?image=https://cdn.romamoulding.com/mouldings/753-1.png which is equivalent to the above.

I suppose the way to do this with Unpic is to allow the domain `images.romamoulding.com` and assert cdn as `cloudflare`. Wouldn't the Regex however block this allowance though?
