### ISSUE TITLE
Trailing slash problem with Astro

### ISSUE THREAD

**Issue by artt** [ascorbic/unpic#141]
Starting from Astro 5 (now in beta), the image endpoint might have trailing slash depending on the `trailingSlash` config. That is, if it's set to `always`, then the image endpoint would be `/_image/`, and `/_image` otherwise. https://github.com/withastro/astro/issues/11568

As I understand, the endpoint is hardcoded here: https://github.com/ascorbic/unpic/blob/bcc18bf350489ede4241495cdb995b00a554c69b/src/transformers/astro.ts#L54

It would be nice if unpic could automatically detect `trailingSlash` settings from Astro config, or at least have an option (passed down from `@unpic/astro`) to set this behavior.

Not sure what's the best way to go about doing that though. Willing to submit a PR if someone could help guide me. Thanks!

**Comment by ascorbic** [comment]
I'm working on it. I need to finish implementing support for components to pass cdn-specific options, and then add an option to set the endpoint. There are a few moving parts.

**Comment by LekoArts** [comment]
Also just hit this issue - I'll use https://pnpm.io/cli/patch for now to change the hardcoded path so that I can continue using `always` for trailingSlash

**Comment by artt** [comment]
> Also just hit this issue - I'll use https://pnpm.io/cli/patch for now to change the hardcoded path so that I can continue using `always` for trailingSlash.
> 
> 
> 
> Edit: Works with the patch. You'll also need to edit this line https://github.com/ascorbic/unpic/blob/bcc18bf350489ede4241495cdb995b00a554c69b/src/transformers/astro.ts#L74

Just learned about this command. Seems very useful. Thank you!

**Comment by ascorbic** [comment]
Thanks for the reports. If you upgrade to the latest `@unpic/astro` it should now respect your trailing slash preference.
