### ISSUE TITLE
Hydration issues with the Lit element

### ISSUE THREAD

**Issue by JulianCataldo** [ascorbic/unpic#143]
Thanks a lot for making this neat library :)

I've encountered an issue, when using Lit SSR and Vite.

Importing `import '@unpic/lit';`

On browser:

```
chunk-5UR36BT3.js?v=1da6385c:155 Uncaught (in promise) Error: Hydration value mismatch: Unexpected TemplateResult rendered to part
    at openChildPart (chunk-5UR36BT3.js?v=1da6385c:155:13)
    at hydrate (chunk-5UR36BT3.js?v=1da6385c:83:26)
    at LitElement.update (@lit-labs_ssr-client….js?v=1da6385c:56:7)
    at UnpicImg2.performUpdate (chunk-7Q6MLD2M.js?v=1da6385c:732:14)
    at UnpicImg2.scheduleUpdate (chunk-7Q6MLD2M.js?v=1da6385c:676:25)
    at UnpicImg2.__enqueueUpdate (chunk-7Q6MLD2M.js?v=1da6385c:652:25)
```

The markup is rendered without problem on both server and client, it is just the hydration step that fails.

Interestingly, if I copy the `unpic-element.ts` in the Vite project and use it instead (after installing the required dep), the hydration issue disappear.

Using `defer-hydration` postpone the problem, but it does not fix it like duplicating the original `.ts` source element.

Same Lit version for the project and the @unpic/lit dependency.

I'll try to find the time to make a detailed repro.

**Comment by ascorbic** [comment]
Thanks for the report. It would be great if you could do a repro!

**Comment by JulianCataldo** [comment]
I just did a minimal repro, and of course, the above hydration problem is not showing up anymore 😅
I couldn't have nailed the cause of this in the "faulty" project.
Since I'm gonna adopt Lit `<unpic-img>` in many places from now, I'll monitor this closely and hope I'll find what's going on.
Also, maybe another user will find this via Google in the future, and see he's not alone 😁

Feel free to close this issue, TY.
