### ISSUE TITLE
Support for Vercel

### ISSUE THREAD

**Issue by benmccann** [ascorbic/unpic#26]
Docs here: https://vercel.com/docs/concepts/image-optimization

I'd love to see support for Vercel. I've been thinking about making a semi-official Svelte image component for awhile. I like the idea of how unpic works and was thinking it might be cool to use it if deploying to Vercel or Cloudflare and fallback to `vite-imagetools` if the user doesn't have a CDN.

**Comment by ascorbic** [comment]
Sure! I'll have a draft PR up this evening my time so it would be good if you could take a look then and see if it would meet your needs.

**Comment by ascorbic** [comment]
@benmccann I have a PR here. Let me know what you think: https://github.com/ascorbic/unpic/pull/32
