### ISSUE TITLE
Feature Request: Directus file transformation API

### ISSUE THREAD

**Issue by jdamboeck** [ascorbic/unpic#36]
Would be great if i could use unpic with the directus file api.

https://docs.directus.io/reference/files.html#preset-transformations
https://docs.directus.io/reference/files.html#advanced-transformations

**Comment by danestves** [comment]
The only downside with Directus is that they don't support `format=auto` for the images, we must be explicit with the format

**Comment by danestves** [comment]
**Update**: Directus supports the format `auto` now, we have a custom transformer in our project to be used with Directus, I'm going to make it a little more perfect and I can do a PR about it
